### ISSUE TITLE
16 Zhang Mahjong II (Taiwan) (Unl)

### ISSUE THREAD

**Issue by hugo19941994** [hugo19941994/megasd-db-generator#1]
Add missing Mega Drive title screenshot:

![16 Zhang Mahjong II (Taiwan) (Unl)](https://user-images.githubusercontent.com/6431131/72667358-4d157000-3a1b-11ea-9a49-6b8fcf8c8a38.png)

[libretro PR](https://github.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/pull/18)

**Comment by TheRealFlamepanther** [comment]
Image added in commit 89db6af20f67022ff9175312e22a6faeb9ef05cb
