### ISSUE TITLE
Screenshot for TwinBee (Taiwan)

### ISSUE THREAD

**Issue by hugo19941994** [hugo19941994/megasd-db-generator#10]
![TwinBee_title](https://user-images.githubusercontent.com/6431131/72750136-4d993c80-3bbc-11ea-8396-a119d9dbb568.png)
https://segaretro.org/TwinBee

**Comment by TheRealFlamepanther** [comment]
Added in commit 70a86875a76bf16cd49d31d22da51a12e1794f50
