### ISSUE TITLE
Penn & Teller doesn't get added to database

### ISSUE THREAD

**Issue by TheRealFlamepanther** [hugo19941994/megasd-db-generator#12]
The unreleased game "Penn & Teller's Smoke and Mirrors" was manually added to the custom Sega CD datfile. The other manually added games appear in db.xml when it is generated, but this one does not.

**Comment by hugo19941994** [comment]
Changed in https://github.com/hugo19941994/megasd-db-generator/commit/da17b3a50e7ea81edeb122e12e474e7c263229ac

Regarding the Space Ace Demo and Dragon's Lair they have the same header names, so their CRCs match (as the MegaSD uses only the first 2KB to calculate it)

![space-ace-demo](https://user-images.githubusercontent.com/6431131/72801513-ecb84580-3c49-11ea-90de-348f5eb0c088.png)
![dragons-lair](https://user-images.githubusercontent.com/6431131/72801521-ede97280-3c49-11ea-97e0-8b0cbc0379c5.png)

**Comment by TheRealFlamepanther** [comment]
Oddly, the Space Ace demo has a different hash in my set (matching what I changed it to).

**Comment by TheRealFlamepanther** [comment]
Penn & Teller still isn't making it into the db.xml

I don't think it's an issue with the hashes, because it's absent from db.xml altogether. I'm looking for anything weird about the tags or the title itself, but I'm not spotting it. It isn't the ampersand, as "Soulstar & Battlecorps" makes it in.

**Comment by TheRealFlamepanther** [comment]
Ah. I assumed the entries would use the "game name" tag as opposed to "rom name"

**Comment by hugo19941994** [comment]
It doesn't, but it's a good suggestion, I will change that. The CRCs of the bin files and the rom has the extension .cue because I didn't bother changing it, so I will take care of that too.

**Comment by TheRealFlamepanther** [comment]
The updated hashes that were added earlier don't match with my disc images when scanning ROMs... which is weird, since I believe there's only one known dump of the game. I found that the hashes currently in the custom DAT match what I get if I add a checksum via Game DB Manager and select the .BIN files instead of the .CUE files. 

I'm not sure how Game DB Manager gets these hashes, as they match neither the CRC32 hashes of the BIN files nor the hash of the first sector obtained from feeding it the cue files. Presumably it needs the hashes found by reading the cue files. I'll test these locally and then update the DAT with them if successful.

Worth noting: the cue files provided by HiddenPalace.org won't work with the Game DB Manager, due to specifying a local drive letter and full path. The drive and path need to be removed, or the Game DB Manager will fail to read the cue file when scanning ROMs or adding hashes.

**Comment by hugo19941994** [comment]
OK, c3ad52c970c9bbe97e45ba92921b76c77acb567a should finally fix it. I modified the CUE files manually.

![IMG_20200126_165517](https://user-images.githubusercontent.com/6431131/73137900-34313e00-405d-11ea-8e0c-f3f0d00b384e.jpg)

Reopen if it's not working again.
