### ISSUE TITLE
Screenshot for Chess (Russia) (Unl)

### ISSUE THREAD

**Issue by hugo19941994** [hugo19941994/megasd-db-generator#7]
![Chess000](https://user-images.githubusercontent.com/6431131/72687246-46125e80-3afc-11ea-96dd-82683ddfd6c6.png)

https://segaretro.org/Chess_(Mega_Drive)

**Comment by TheRealFlamepanther** [comment]
Added in commit de47a413ca5018fb17f04d409fc18ae3d359a03a
