### ISSUE TITLE
Screenshot for Gun.Smoke (Korea) (Unl)

### ISSUE THREAD

**Issue by hugo19941994** [hugo19941994/megasd-db-generator#8]
![GunSmoke_title](https://user-images.githubusercontent.com/6431131/72688080-4dd60100-3b04-11ea-9e3d-92c8aacd15a4.png)

https://segaretro.org/Gun.Smoke

**Comment by TheRealFlamepanther** [comment]
Added in commit 2ca2f74555ba7c0ca274e82ecc1e4b494abc7009
