### ISSUE TITLE
Screenshot for Yie Ar Kung-Fu II (Taiwan)

### ISSUE THREAD

**Issue by hugo19941994** [hugo19941994/megasd-db-generator#9]
![YieArKungFuII_title](https://user-images.githubusercontent.com/6431131/72747818-f6906900-3bb5-11ea-9da9-fb6d3819ed81.png)

https://segaretro.org/Yie_Ar_Kung-Fu_II

**Comment by TheRealFlamepanther** [comment]
Added in commit 70a86875a76bf16cd49d31d22da51a12e1794f50
